"""
Database models and connection management for AEGIS.

Uses SQLAlchemy with TimescaleDB extension for efficient time-series storage.
Implements async operations for high-performance data access.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, ForeignKey, Index, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.pool import NullPool
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from datetime import datetime
from typing import Optional, List, AsyncGenerator
import numpy as np

from ..config.settings import settings

Base = declarative_base()


class OHLCV(Base):
    """
    OHLCV (Open-High-Low-Close-Volume) price data table.
    
    Optimized for TimescaleDB hypertable conversion.
    Stores minute-level and daily-level data for all asset classes.
    """
    
    __tablename__ = 'ohlcv'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(50), nullable=False, index=True)
    timeframe = Column(String(10), nullable=False, index=True)  # 1m, 5m, 1h, 1d, etc.
    
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    
    # Additional fields for derivatives
    open_interest = Column(Float, nullable=True)  # Futures/Options
    funding_rate = Column(Float, nullable=True)   # Crypto perpetuals
    
    # Metadata
    source = Column(String(50), default='api')
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_ohlcv_symbol_time', 'symbol', 'timestamp'),
        Index('idx_ohlcv_exchange_timeframe', 'exchange', 'timeframe'),
    )
    
    def to_dict(self) -> dict:
        return {
            'id': self.id,
            'timestamp': self.timestamp.isoformat(),
            'symbol': self.symbol,
            'exchange': self.exchange,
            'timeframe': self.timeframe,
            'open': self.open,
            'high': self.high,
            'low': self.low,
            'close': self.close,
            'volume': self.volume,
            'open_interest': self.open_interest,
            'funding_rate': self.funding_rate
        }


class TickData(Base):
    """
    Tick-level market data for high-frequency analysis.
    
    Stores individual trades and quote updates.
    Used for microstructure features and backtesting accuracy.
    """
    
    __tablename__ = 'tick_data'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(50), nullable=False)
    
    # Trade data
    price = Column(Float, nullable=True)
    volume = Column(Float, nullable=True)
    side = Column(String(10), nullable=True)  # 'buy' or 'sell'
    trade_id = Column(String(100), nullable=True, unique=True)
    
    # Quote data
    bid_price = Column(Float, nullable=True)
    ask_price = Column(Float, nullable=True)
    bid_size = Column(Float, nullable=True)
    ask_size = Column(Float, nullable=True)
    
    # Order book snapshot (optional, stored as JSON)
    order_book = Column(JSONB, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_tick_symbol_time', 'symbol', 'timestamp'),
    )


class Feature(Base):
    """
    Pre-computed features stored in the feature store.
    
    Avoids recomputation during backtesting and live trading.
    Supports multiple feature types and versions.
    """
    
    __tablename__ = 'features'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    feature_name = Column(String(100), nullable=False, index=True)
    feature_version = Column(String(20), default='v1')
    
    value = Column(Float, nullable=False)
    metadata = Column(JSONB, nullable=True)  # Feature computation parameters
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_feature_symbol_time_name', 'symbol', 'timestamp', 'feature_name'),
    )


class Signal(Base):
    """
    Trading signals generated by strategies.
    
    Tracks signal history for performance attribution and analysis.
    """
    
    __tablename__ = 'signals'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    symbol = Column(String(50), nullable=False, index=True)
    strategy_name = Column(String(100), nullable=False, index=True)
    
    signal_value = Column(Float, nullable=False)  # -1 to 1 (short to long)
    confidence = Column(Float, nullable=True)  # Model confidence score
    target_horizon = Column(Integer, nullable=True)  # Prediction horizon in bars
    
    # Signal components
    alpha_components = Column(JSONB, nullable=True)  # Breakdown of signal sources
    
    # Metadata
    model_version = Column(String(50), nullable=True)
    features_used = Column(JSONB, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_signal_strategy_time', 'strategy_name', 'timestamp'),
    )


class Order(Base):
    """
    Order tracking for execution management.
    
    Records all order lifecycle events from submission to fill/cancellation.
    """
    
    __tablename__ = 'orders'
    
    id = Column(Integer, primary_key=True)
    order_id = Column(String(100), unique=True, nullable=False, index=True)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    
    # Order details
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(50), nullable=False)
    strategy_name = Column(String(100), nullable=True)
    
    side = Column(String(10), nullable=False)  # 'buy' or 'sell'
    order_type = Column(String(20), nullable=False)  # 'market', 'limit', 'stop'
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=True)  # Limit price
    stop_price = Column(Float, nullable=True)  # Stop price
    
    # Order status
    status = Column(String(20), nullable=False, index=True)  # 'pending', 'partial', 'filled', 'cancelled', 'rejected'
    filled_quantity = Column(Float, default=0)
    average_fill_price = Column(Float, nullable=True)
    
    # Execution details
    fills = Column(JSONB, nullable=True)  # List of individual fills
    commission = Column(Float, default=0)
    slippage = Column(Float, nullable=True)
    
    # Timing
    submitted_at = Column(DateTime, nullable=True)
    filled_at = Column(DateTime, nullable=True)
    cancelled_at = Column(DateTime, nullable=True)
    
    # Error handling
    error_message = Column(Text, nullable=True)
    retry_count = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_order_symbol_status', 'symbol', 'status'),
    )


class Position(Base):
    """
    Current portfolio positions.
    
    Tracks open positions with real-time PnL calculation.
    """
    
    __tablename__ = 'positions'
    
    id = Column(Integer, primary_key=True)
    symbol = Column(String(50), unique=True, nullable=False, index=True)
    exchange = Column(String(50), nullable=False)
    
    # Position details
    quantity = Column(Float, nullable=False, default=0)
    average_entry_price = Column(Float, nullable=True)
    current_price = Column(Float, nullable=True)
    
    # PnL tracking
    unrealized_pnl = Column(Float, default=0)
    realized_pnl = Column(Float, default=0)
    total_pnl = Column(Float, default=0)
    
    # Risk metrics
    position_value = Column(Float, default=0)
    weight = Column(Float, default=0)  # Portfolio weight
    
    # Timestamps
    opened_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_position_symbol', 'symbol'),
    )


class PortfolioSnapshot(Base):
    """
    Daily portfolio snapshots for performance tracking.
    
    Enables historical portfolio analysis and reporting.
    """
    
    __tablename__ = 'portfolio_snapshots'
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, index=True)
    
    # Portfolio metrics
    total_value = Column(Float, nullable=False)
    cash_balance = Column(Float, nullable=False)
    positions_value = Column(Float, nullable=False)
    
    # Returns
    daily_return = Column(Float, nullable=True)
    cumulative_return = Column(Float, nullable=True)
    
    # Risk metrics
    volatility = Column(Float, nullable=True)
    sharpe_ratio = Column(Float, nullable=True)
    max_drawdown = Column(Float, nullable=True)
    current_drawdown = Column(Float, nullable=True)
    
    # Exposure
    gross_exposure = Column(Float, nullable=True)
    net_exposure = Column(Float, nullable=True)
    leverage = Column(Float, nullable=True)
    
    # Position count
    long_positions = Column(Integer, default=0)
    short_positions = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_snapshot_time', 'timestamp'),
    )


class ModelMetadata(Base):
    """
    ML model metadata and versioning.
    
    Tracks model versions, hyperparameters, and performance metrics.
    """
    
    __tablename__ = 'model_metadata'
    
    id = Column(Integer, primary_key=True)
    model_name = Column(String(100), nullable=False, index=True)
    model_version = Column(String(50), nullable=False)
    
    # Model type
    model_type = Column(String(50), nullable=False)  # 'xgboost', 'lstm', 'transformer', etc.
    
    # Hyperparameters
    hyperparameters = Column(JSONB, nullable=True)
    
    # Training info
    training_start = Column(DateTime, nullable=True)
    training_end = Column(DateTime, nullable=True)
    training_samples = Column(Integer, nullable=True)
    features_used = Column(JSONB, nullable=True)
    
    # Performance metrics
    train_metrics = Column(JSONB, nullable=True)
    validation_metrics = Column(JSONB, nullable=True)
    test_metrics = Column(JSONB, nullable=True)
    walk_forward_metrics = Column(JSONB, nullable=True)
    
    # Model status
    status = Column(String(20), default='training')  # 'training', 'ready', 'deployed', 'deprecated'
    is_active = Column(Boolean, default=False)
    
    # Storage
    model_path = Column(String(500), nullable=True)
    mlflow_run_id = Column(String(100), nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    deployed_at = Column(DateTime, nullable=True)
    
    __table_args__ = (
        Index('idx_model_name_version', 'model_name', 'model_version'),
    )


class DatabaseManager:
    """
    Database connection and session management.
    
    Provides async session management and database initialization.
    """
    
    def __init__(self):
        self.engine = None
        self.async_session_maker = None
        self._initialized = False
    
    async def initialize(self):
        """Initialize database connection and create tables."""
        if self._initialized:
            return
        
        self.engine = create_async_engine(
            settings.database.sqlalchemy_url,
            pool_pre_ping=True,
            echo=settings.debug,
            pool_size=settings.database.pool_size,
            max_overflow=settings.database.max_overflow
        )
        
        self.async_session_maker = async_sessionmaker(
            self.engine,
            class_=AsyncSession,
            expire_on_commit=False
        )
        
        # Create tables (in production, use migrations with Alembic)
        async with self.engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
        
        self._initialized = True
    
    async def get_session(self) -> AsyncGenerator[AsyncSession, None]:
        """Get async database session."""
        if not self._initialized:
            await self.initialize()
        
        async with self.async_session_maker() as session:
            try:
                yield session
                await session.commit()
            except Exception:
                await session.rollback()
                raise
            finally:
                await session.close()
    
    async def close(self):
        """Close database connections."""
        if self.engine:
            await self.engine.dispose()
            self._initialized = False


# Global database manager instance
db_manager = DatabaseManager()


async def get_db_session() -> AsyncGenerator[AsyncSession, None]:
    """Dependency for FastAPI to get database session."""
    async for session in db_manager.get_session():
        yield session
